import type { Metadata, Viewport } from "next";
import AuthProvider from "@/components/auth/AuthProvider";
import { Quicksand } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/context/ThemeProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import { UserAdminRepository } from "@/repositories/admin/userAdminRepository";
import "./globals.css";

const quicksand = Quicksand({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-quicksand",
});

export const metadata: Metadata = {
  title: "Fluency Lab",
  description: "Generated by create next app",
  appleWebApp: {
    statusBarStyle: "black-translucent",
  },
};

export const viewport: Viewport = {
  initialScale: 1,
  viewportFit: "cover",
  userScalable: false,
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  let themeColorClass = "theme-violet";

  if (session?.user?.id) {
    const userAdminRepo = new UserAdminRepository();
    const user = await userAdminRepo.findUserById(session.user.id);
    if (user?.themeColor) {
      themeColorClass = `theme-${user.themeColor}`;
    }
  }

  return (
    <html lang="en" suppressHydrationWarning className={themeColorClass}>
      <body className={quicksand.className}>
        <AuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
